[project]
name = "party-planner-frontend"
version = "0.1.0"
description = "Streamlit frontend for party planning assistant"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "streamlit>=1.28.0",
    "requests>=2.31.0",
    "python-dotenv>=1.1.1",
]
